# Veri Bilimi için Programlama

## Vektörler - Matrisler - Tensör ve Diziler

Dr. Murat Gezer

**NumPy** , Python programlama dili için geliştirilmiştir bir kütüphanedir. NumPy, Python'u bilimsel hespalama için  aritmetik ve sayısal hesaplamalar için işlevlerle genişletir. Kitaplık, matrisler, çok boyutlu diziler ve vektörlerle verimli hesaplama yapılmasını sağlamaktadır. Numpy dizileri devamlı olarak aynı veri türünde olmak durumundadır

Ana özellikleri ve avantajları şu şekildedir ;

- Güçlü bir N-boyutlu dizi nesnesi
- Sofistike fonksiyonlar
- Donanıma daha yakın (verimlilik)
- Bilimsel hesaplama için tasarlanmış (kolaylık)
 - C / C ++ ve Fortran kodunu bütünleştirme araçları
 - lineer cebir, Fourier dönüşümü ve rastgele sayı 

Eğer hızlı şekilde nümerik işlem yapacak ise bize daha hızlı şekilde hafızada alan açıp yapacaktır. Örneğin bilgisayarımızda ilk 10000000 sayının karesini almak  istersek;

In [2]:
import numpy as np 
L = range(10000000)
%timeit [i**2 for i in L]
a = np.arange(10000000)
%timeit a**2

L

3.03 s ± 8.81 ms per loop (mean ± std. dev. of 7 runs, 1 loop each)
15.4 ms ± 44.6 µs per loop (mean ± std. dev. of 7 runs, 100 loops each)


range(0, 10000000)

### Dizi Oluşturma

- #### 1-D dizi oluşturma

In [3]:
# Kütüphane yükleme
import numpy as np

# Satir vektoru oluşturma (row vector)
satirVektoru = np.array([0, 1, 2, 3])

#Sütun vektörü oluşturma (column vector)
sutunVektoru=np.array([[0],[1],[2],[3]])

print(satirVektoru)
print(sutunVektoru)

[0 1 2 3]
[[0]
 [1]
 [2]
 [3]]


- #### 2-D dizi oluşturma

In [5]:
matris=np.array([[1,2,3],[3,4,8],[5,6,9]])
print(matris)

[[1 2 3]
 [3 4 8]
 [5 6 9]]


Bir dizinin rankını bulma ve dizinin boyutu

In [6]:
print(".ndim",matris.ndim) # Dizinin eksenlerinin (boyutları) sayısı. Python dünyasında, boyutların sayısına rank denir.

print("shape",matris.shape) #Dizinin boyutları. Bu, her boyutta dizinin boyutunu belirten bir tamsayı yığınıdır.
#N sıralı ve m sütunlu bir matris için matris(n, m) olacaktır. 
#Bu nedenle, matris dizesinin uzunluğu sırası veya boyut sayısıdır, ndim.

.ndim 2
shape (3, 3)


- Dizinin boyutunu bulmak : ndarray.ndim
.ndim →numpy array nesnesinin boyutunu döndürür.

- Dizinin satır ve sütun sayısını bulmak: ndarray.shape
.shape →Numpy array nesnesinin kaç satır ve sütundan oluştuğunu gösteren bir tupple nesnesi döndürür.

Bununla birlikte, matris veri yapısı iki nedenden dolayı önerilmemektedir. İlk diziler, Numpy'nin standart standart veri yapısıdır. İkincisi, Numpy işlemlerinin büyük çoğunluğu matris nesnelerini değil dizi döndürür

### Vektör ya da Matris İçinden Eleman Seçimi
Matris veya vektör kümeleri içinden aşağıdaki gibi bir ya da daha fazla elemana erişebilirsiniz.

In [7]:
# Kütüphane yükleme
import numpy as np

# Satir vektoru oluşturma (row vector)
a = np.array([1, 2, 3,4,5,6,7,8,9,10])
# Bir A matrisi oluşturalım
A=np.array([[1,2,3],[4,5,6],[7,8,9]])

In [10]:
# Vektörün 3. elemanını seçelim

print ("a vektörüm=",a)
print("\n")
print("vektörün 3. elemanı=",a[2])


a vektörüm= [ 1  2  3  4  5  6  7  8  9 10]


vektörün 3. elemanı= 3


In [16]:
# Bir matrisin 2. satir 3. sütununu seçmek istersel
#print ("A matrisi=\n",A)
print("\n")
print("A matisinin 2. satırı ve 3. sütunu:",A[1,2])



A matisinin 2. satırı ve 3. sütunu: 6


In [17]:
# Bir vektörden tüm elemanların çekilmesi
#print(a[:])
# vektörde seçilen elemana kadar olan değerlerin getirlmesi
print(a[:3])
# vektörde seçilen elemandan sonra olan değerlerin getirlmesi
print(a[4:])

[1 2 3]
[ 5  6  7  8  9 10]


In [15]:
# Matris içinde seçilen satıra (2. satır) ve ondan sonra gelen satırlar için
# tüm sütun elemanlarının getirilmesi
print(A[:2,:])

[[1 2 3]
 [4 5 6]]


In [18]:
# Matristeki seçilen sütuna ait değerlerin getirilmesi
print(A[:,1:2])


[[2]
 [5]
 [8]]


#### Matris İşlemleri -1


Python'da farklı matris işlemlerini ve işlemlerini çözülebilir.


**add ()**  veya **+** - iki matrisi toplar

**subtract ()** veya **-** - iki matrisde çıkartma işlemi

**divide ()** veya **/** - iki matrisde eleman bölme işlemi

**multiply ()** veya  *  - iki matrisde eleman çarpma işlemi

**dot ()** **@** - Matris çarpımını gerçekleştirir



**sum (x, eksen)** - matristeki tüm elemanların toplamı . İkinci argüman isteğe bağlıdır, eksen 0 ise sütun toplamını ve eksen 1 ise satır toplamını hesaplamak istediğimizde kullanılır.

**T** - Belirtilen matrisin transpozesi

In [19]:
# Kütüphane yükleme
import numpy as np
# Bir A matrisi oluşturalım
A = np.array([[1, 2], [4, 5]])
# Bir B matrisi oluşturalım
B = np.array([[2, 8], [4, 2]])

In [23]:
print (A,"\n",B)
#  toplama işlemi
print ("iki matrisin toplamı (A+B): ")
print (np.add(A,B))

#  çıkarma işlemi
print ("iki matrisin farkı (A-B): ")
print (np.subtract(A,B))

# çarpma işlemi
print ("iki matrisin eleman çarpımı: ")
print (np.multiply(A,B))

# çarpma işlemi
print ("iki matrisin çarpımı: ")
print (np.multiply(A,B))

# bölme işlemi
print ("iki matrisin bölümü: ")
print (np.divide(A,B))

# matris çarpımı işlemi
print ("iki matrisin matris çarpımı: ")
print (np.dot(A,B))

# matris elemanların toplamı
print ("matrisin elemanlarının toplam değeri: ")
print (np.sum(A))

# matris satır elemanların toplamı
print ("matrisin satır elemanlarının toplam değeri: ")
print (np.sum(A,1))
# matris sütun elemanların toplamı
print ("matrisin sütun elemanlarının toplam değeri: ")
print (np.sum(A,0))


[[1 2]
 [4 5]] 
 [[2 8]
 [4 2]]
iki matrisin toplamı (A+B): 
[[ 3 10]
 [ 8  7]]
iki matrisin farkı (A-B): 
[[-1 -6]
 [ 0  3]]
iki matrisin eleman çarpımı: 
[[ 2 16]
 [16 10]]
iki matrisin çarpımı: 
[[ 2 16]
 [16 10]]
iki matrisin bölümü: 
[[0.5  0.25]
 [1.   2.5 ]]
iki matrisin matris çarpımı: 
[[10 12]
 [28 42]]
matrisin elemanlarının toplam değeri: 
12
matrisin satır elemanlarının toplam değeri: 
[3 9]
matrisin sütun elemanlarının toplam değeri: 
[5 7]


#### Matris İşlemleri -2 Veri Manipülasyonu 


**T** - Belirtilen matrisin transpozesi

**reshape** yeniden şekillendir

**flatten** tek boyuta dönüştürme

In [25]:
# matris'in Transpozesi
print ("matrisin transpozesi: ")
print (A.T)
C=np.array([[1,2,3,4],[5,6,7,8],[9,10,11,12],[13,14,15,16]])

print("\nC=\n",C)
print(C.reshape(8,2))     

print(C.flatten())

matrisin transpozesi: 
[[1 4]
 [2 5]]

C=
 [[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]
 [13 14 15 16]]
[[ 1  2]
 [ 3  4]
 [ 5  6]
 [ 7  8]
 [ 9 10]
 [11 12]
 [13 14]
 [15 16]]
[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16]


#### Bir Matrisin Köşegenini (Diagonel) Alma

**diagonal** köşegen

**diagonal(offset=1)** üst köşegen

**diagonal(offset=-1)** alt  köşegen

In [29]:
C=np.array([[1,2,3,4],[5,6,7,8],[9,10,11,12],[13,14,15,16]])

print(C,"\n")
print(C.diagonal(offset=-1))

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]
 [13 14 15 16]] 

[ 5 10 15]


#### Dizi Oluşturma İşlevleri

Uygulamada, nadiren elemanları  tek tek gireriz,

eşit araklı dizi oluşturmak için 

**arange(n)**  0 dan n-1 kadar değer sahip dizi

**arrange(baslangic,bitis,adım)**  baslangıçtan bitişe kadar adım aralıklı dizi oluştur 

**linspace(baslangic,bitiş,noktasayısı)** 

In [33]:
a = np.arange(10) #0 dan n-1
#print(a)

print("\n")
A = np.arange(12).reshape(3,4)  # 2 boyutlu (matris)
#print (A)

print("\n")
T = np.arange(24).reshape(2, 3, 4)  # 3 boyutlu dizi (tensor)
#print (T)

In [35]:
print(np.arange(10000))

print("\n")

#print(np.arange(10000).reshape(100,100))

[   0    1    2 ... 9997 9998 9999]




In [34]:
b = np.arange(1, 9, 2)
c = np.linspace(0, 1, 6)

print(b)
print("\n")
print(c)

[1 3 5 7]


[0.  0.2 0.4 0.6 0.8 1. ]


**ones**, **zeros**,**eye** ve **diag**ile dizi oluşturma

In [56]:
#print(np.ones((2,2)))
print("\n")

#print(np.zeros((4,4)))
print("\n")

#print(np.eye(3))
print("\n")

#print(np.diag(np.array([3,4])))

In [53]:
# Rastlantısal sayı üretici (Mersene Twister rastgele sayı üreticisi)

np.random.seed(12)  # Rastgele tohum belirleme

a = np.random.rand(4) #uniform dağılım [0-1]
print(a)
print("\n")
b = np.random.randn(4) #gaussian dağılım 
print(b)
print("\n")
c = np.floor(np.random.random((4,4))*10).astype('int8') #
print(c)
print("\n")

print(c.dtype)

[0.15416284 0.7400497  0.26331502 0.53373939]


[ 0.75314283 -1.53472134  0.00512708 -0.12022767]


[[5 4 7 1]
 [7 0 1 1]
 [3 6 4 8]
 [2 7 7 3]]


int8


numpy'ın ön tanımlı veri tipi float olmaktadır.

'?'
boolean
'b'
(signed) byte
'B'
unsigned byte
'i'
(signed) integer
'u'
unsigned integer
'f'
floating-point
'c'
complex-floating point
'm'
timedelta
'M'
datetime
'O'
(Python) objects
'S', 'a'
zero-terminated bytes (not recommended)
'U'
Unicode string
'V'
raw data (void)
float64
int32
int64
uint32
uint64



In [88]:
import numpy as np 
  
# Veri türü ile dizi oluşturma 
dizi1 = np.array([-1,0,1,2,3,4,5,6,65537],dtype='?') 
  

print("dizi:", dizi1) 
print("veritürü:", dizi1.dtype) 

dizi: [ True False  True  True  True  True  True  True  True]
veritürü: bool


In [ ]:
# S, dize veri türünü tanımlamak için kullanılır. 
# Boyutlarıyla birlikte çeşitli diğer veri türlerini tanımlamak için i, u, f, S ve U kullanırız.



import numpy as np 
  
# veri türü ve boyutu 8, yani 64 bayt ile birlikte dizi oluşturma ve başlatma
arr = np.array([1, 2, 3, 4], dtype='i8') 

print('Dizi:', arr) 
print('Veri Türü:', arr.dtype) 

In [62]:

def is_Power_of_two(n):
        return n > 0 and (n & (n - 1)) == 0
    
bit 1 & 0 = 1
bit 11 & 10 = 10 1  

n=3   100
n-1=2 011

11
10

10

False